# The Robert and Rosenbaum Uncertainty Zones model

## Implementation by 
## Marcos Costa Santos Carreira
## École Polytechnique - CMAP
## Dec-2019

## Import packages

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from functools import partial
import scipy.stats as st
import seaborn as sns
from scipy import optimize

In [2]:
# import ruptures as rpt

In [3]:
# import datetime as dtt
import timeit

In [4]:
import uz as uz

In [5]:
#import cProfile
# useful to check bottlenecks
# But the biggest improvement is to parallelize \
#     the Monte Carlo simulations

In [6]:
pd.set_option('display.max_columns', 80)

## File paths

In [7]:
# pathdata='/Users/marcoscscarreira/Documents/X/CME project/data/'
# pathdfs='/Users/marcoscscarreira/Documents/X/CME project/dfs/'
pathdfs='/Users/marcoscscarreira/My Papers/UZModelUncertainty/dfs/'
# useful to store the raw paths, the processed paths and the statistics

## Simulations

### Parameters

In [8]:
# npaths = 50 # should be enough?
# npaths = 2
# Spot = 100.
# tm = 1. # one trading day
# dt = 0.005 # step 0.005s=5ms
# hours = 8 # a trading day for stocks
# dtosec = np.sqrt(hours*3600)
# nrsteps = int(np.round((dtosec**2)/dt))
# tmrst = uz.atrange(nrsteps,tm)

In [9]:
npaths = 1
s = 100.
tm = 1. # one trading day
dt = 0.005 # step 0.005s=5ms
nrsteps = 2**23 # 2**23
hours = dt*(nrsteps)/3600 # a trading day for stocks
dtosec = np.sqrt(hours*3600)
tmrst = uz.atrange(nrsteps, tm)
hours = 9
tmrstsec = tmrst * hours * 3600

In [10]:
# vollist   = [0.00125, 0.0025, 0.005, 0.01, 0.02] # For the trading hours
# alphalist = [0.005, 0.01, 0.02, 0.04]
# etalist   = [0.0, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5]
# mulist = [-0.03, -0.02, -0.01, -0.005, 0.0, +0.005, +0.01, +0.02, +0.03]
# spotlist = [97., 98., 99., 99.5, 99.75, 100., 100.25, 100.5, 101., 102., 103.]

The durations can be estimated by the formula:

$2\cdot\eta\cdot\left(\frac{\alpha}{S}\cdot\frac{1}{\sigma}\right)^{2}$

In [11]:
# durlist = np.array([[v, a, e, uz.dur(Spot, a, e, v)] \
#                        for e in etalist \
#                        for a in alphalist \
#                        for v in vollist])

In [12]:
# durdf=pd.DataFrame(durlist,columns=['vol','alpha','eta','dur'])
# durdf['dursec']=durdf['dur']*dtosec**2

We want to make sure our simulation has steps small enough to capture
the durations for $\eta$=0.1

In [13]:
# durdf[durdf['eta']==0.1].set_index(['vol','alpha','eta']).sort_index()

In [14]:
# durdf.set_index(['vol','alpha','eta']).sort_index()

### Raw paths - Generation

In [15]:
seed = 42

In [16]:
rndns = uz.frndn(nrsteps, seed)

In [17]:

σ = 0.01
μ = 0.
σ2 = 0.02
μ2 = 0.05
σ3 = 0.05
μ3 = 0.0004*(9*60)
v = np.full(nrsteps, σ)
mu = np.full(nrsteps, μ)
v1 = np.concatenate((np.full(nrsteps//2, σ), np.full(nrsteps//2, σ2)))
mu1 = np.concatenate((np.full(nrsteps//2, μ), np.full(nrsteps//2, μ2)))
v2 = np.concatenate((np.full(nrsteps//2-500000, σ),
                     np.full(1000000, σ3),
                     np.full(nrsteps//2-500000, σ)))
mu2 = np.concatenate((np.full(nrsteps//2-500000, μ),
                      np.full(1000000, μ3),
                      np.full(nrsteps//2-500000, μ)))

In [18]:
# pd.Series(v, index=tmrst[:-1]).plot(figsize=(9, 6), color='k');
# pd.Series(v1, index=tmrst[:-1]).plot(figsize=(9, 6), color='g');
# pd.Series(v2, index=tmrst[:-1]).plot(figsize=(9, 6), color='b');

In [19]:
# pd.Series(mu, index=tmrst[:-1]).plot(figsize=(9, 6), color='k');
# pd.Series(mu1, index=tmrst[:-1]).plot(figsize=(9, 6), color='g');
# pd.Series(mu2, index=tmrst[:-1]).plot(figsize=(9, 6), color='b');

In [20]:
# tmrst = uz.atrange(nrsteps, tm)
# tmrst = uz.atrange(nrsteps, tm)

In [21]:
path0 = uz.MCPath(rndns, v, s, tm, mu)  # Black, trend 0 vol 0.01
path1 = uz.MCPath(rndns, v1, s, tm, mu)  # Green, vol from 0.01 to 0.02
path2 = uz.MCPath(rndns, v, s, tm, mu1)  # Blue, trend from 0 to 0.05
path3 = uz.MCPath(rndns, v1, s, tm, mu1)  # Magenta, both changes
path4 = uz.MCPath(rndns, v, s, tm, mu2)  # Red, burst
path5 = uz.MCPath(rndns, v2, s, tm, mu2)  # Yellow, burst with vol

In [22]:
# pd.Series(path0, index=tmrst).plot(figsize=(9, 6), color='k');
# pd.Series(path1, index=tmrst).plot(figsize=(9, 6), color='g');
# pd.Series(path2, index=tmrst).plot(figsize=(9, 6), color='b');
# pd.Series(path3, index=tmrst).plot(figsize=(9, 6), color='m');
# pd.Series(path4, index=tmrst).plot(figsize=(9, 6), color='r');
# pd.Series(path5, index=tmrst).plot(figsize=(9, 6), color='y');

In [23]:

# signal = np.transpose(np.array([path0, path1, path2, path3]))

In [24]:

# algo = rpt.Pelt(model='l2', min_size=100).fit(signal)
# my_bkps = algo.predict(pen=10)

In [25]:

# rpt.display(signal, my_bkps)

In [26]:

α = 0.01
η = 0.3
trpath0 = uz.trprpath(α, η, path0)
trpath1 = uz.trprpath(α, η, path1)
trpath2 = uz.trprpath(α, η, path2)
trpath3 = uz.trprpath(α, η, path3)
trpath4 = uz.trprpath(α, η, path4)
trpath5 = uz.trprpath(α, η, path5)

In [27]:
# pd.Series(trpath0, index=tmrst).plot(figsize=(9, 6), color='k');
# pd.Series(trpath1, index=tmrst).plot(figsize=(9, 6), color='g');
# pd.Series(trpath2, index=tmrst).plot(figsize=(9, 6), color='b');
# pd.Series(trpath3, index=tmrst).plot(figsize=(9, 6), color='m');
# pd.Series(trpath4, index=tmrst).plot(figsize=(9, 6), color='r');
# pd.Series(trpath5, index=tmrst).plot(figsize=(9, 6), color='y');

In [28]:

# signal_tr = np.transpose(np.array([trpath0, trpath1, trpath2, trpath3]))

In [29]:

# algo_tr = rpt.Pelt(model='l2', min_size=100).fit(signal_tr)
# my_bkps_tr = algo_tr.predict(pen=3)

In [30]:

# rpt.display(signal_tr, my_bkps_tr)

In [31]:

pxchg0 = uz.diff_prices_df_nogroup(pd.Series(trpath0, index=tmrstsec), α)
pxchg1 = uz.diff_prices_df_nogroup(pd.Series(trpath1, index=tmrstsec), α)
pxchg2 = uz.diff_prices_df_nogroup(pd.Series(trpath2, index=tmrstsec), α)
pxchg3 = uz.diff_prices_df_nogroup(pd.Series(trpath3, index=tmrstsec), α)
pxchg4 = uz.diff_prices_df_nogroup(pd.Series(trpath4, index=tmrstsec), α)
pxchg5 = uz.diff_prices_df_nogroup(pd.Series(trpath5, index=tmrstsec), α)

In [32]:
uz.distance_dur(pxchg0, s, α, η, σ, μ, hours)

0.4552553260013474

In [33]:
hour_range = range(1, hours + 1)
min_range = range(10, hours*60 + 10, 10)

In [34]:
# start = timeit.default_timer()
# res0de = uz.minde_dist(pxchg0, s, α, hours)
# stop = timeit.default_timer()
# print('Time Spent: ', round(stop - start), ' seconds')
# df0_res = pd.DataFrame([res0de], index=[0],
#                        columns=['H', 'η', 'σ', 'σXe', 'σP', 'μ', 'μmax', 'distance'])
# print(df0_res)

In [35]:
# start = timeit.default_timer()
# res0de = uz.minde_dist(pxchg0, s, α, hours, 0.01)
# stop = timeit.default_timer()
# print('Time Spent: ', round(stop - start), ' seconds')
# df0_res = pd.DataFrame([res0de], index=[0],
#                        columns=['H', 'η', 'σ', 'σXe', 'σP', 'μ', 'μmax', 'distance'])
# print(df0_res)

In [42]:
start = timeit.default_timer()
res0dmf = uz.multfit_dist(pxchg0, s, α, hours, 'All', 0)
stop = timeit.default_timer()
print('Time Spent: ', round(stop - start), ' seconds')

Time Spent:  87  seconds

In [43]:
res0dmf.T

                 All
Al_Up       0.304947
Co_Up       0.194110
Al_Do       0.305012
Co_Do       0.195931
Al          0.609959
Co          0.390041
Al_Co_dist  0.114590
H           0.319727
Al_Up_η     0.317355
Co_Up_η     0.301549
Al_Do_η     0.312560
Co_Do_η     0.306140
Al_η        0.314701
Co_η        0.302660
Al_Co_η     0.320970
σP          0.012452
σXe         0.009957
Al_Up_σ     0.009853
Co_Up_σ     0.009638
Al_Do_σ     0.009963
Co_Do_σ     0.009318
Al_σ        0.009918
Co_σ        0.009585
Al_Co_σ     0.009938
μmax       -0.071884
Al_Up_μ     0.000666
Co_Up_μ     0.011271
Al_Do_μ    -0.071788
Co_Do_μ     0.039063
Al_μ        0.062931
Co_μ        0.002173
Al_Co_μ     0.002893

In [44]:
start = timeit.default_timer()
res0_tbl = [uz.multfit_dist(pxchg0.loc[:h*3600], s, α, hours, h)
             for h in hour_range]
stop = timeit.default_timer()
print('Time Spent: ', round(stop - start), ' seconds')

In [45]:
df0_rest = pd.concat(res0_tbl, axis=0)

In [46]:
df0_rest.T

,1,2,3,4,5,6,7,8,9
Al_Up,0.294560,0.300530,0.304450,0.303680,0.304215,0.305063,0.304140,0.305171,0.304947
Co_Up,0.196759,0.188863,0.188720,0.191961,0.193784,0.193125,0.194184,0.193839,0.194110
Al_Do,0.294560,0.300825,0.304645,0.303827,0.304332,0.305063,0.304140,0.305244,0.305012
Co_Do,0.214120,0.209782,0.202186,0.200532,0.197669,0.196749,0.197536,0.195746,0.195931
Al,0.589120,0.601355,0.609094,0.607507,0.608547,0.610126,0.608280,0.610414,0.609959
Co,0.410880,0.398645,0.390906,0.392493,0.391453,0.389874,0.391720,0.389586,0.390041
Al_Co_dist,0.318014,0.261947,0.206255,0.239160,0.222247,0.166668,0.147321,0.117999,0.114589
H,0.348723,0.331455,0.320891,0.323036,0.321629,0.319502,0.321990,0.319116,0.319727
Al_Up_η,0.317661,0.308099,0.304759,0.313593,0.317305,0.317112,0.311655,0.311855,0.317232
Co_Up_η,0.242683,0.322270,0.289011,0.274193,0.264850,0.282048,0.296442,0.297178,0.301652
Al_Do_η,0.310920,0.288598,0.305156,0.310633,0.316695,0.313782,0.316959,0.319200,0.312607
Co_Do_η,0.353762,0.298808,0.274642,0.285027,0.292556,0.291212,0.296139,0.304980,0.306761
Al_η,0.314293,0.295604,0.305211,0.311216,0.317038,0.315220,0.315112,0.316251,0.314492
Co_η,0.293605,0.313764,0.286078,0.275541,0.273159,0.284274,0.296080,0.299115,0.302480
Al_Co_η,0.391943,0.346873,0.310912,0.316255,0.316105,0.316903,0.318152,0.317940,0.321091
σP,0.012494,0.012410,0.012455,0.012401,0.012426,0.012432,0.012442,0.012438,0.012452
σXe,0.010434,0.010104,0.009978,0.009968,0.009966,0.009938,0.009985,0.009937,0.009957
Al_Up_σ,0.010168,0.009674,0.009557,0.009642,0.009715,0.009769,0.009730,0.009751,0.009851
Co_Up_σ,0.008243,0.009844,0.009372,0.009266,0.009425,0.009720,0.008960,0.009867,0.009361
Al_Do_σ,0.010227,0.009791,0.009895,0.010003,0.010066,0.009973,0.010046,0.010023,0.009964
Co_Do_σ,0.010076,0.008480,0.008513,0.008536,0.009866,0.008902,0.009814,0.010164,0.010208
Al_σ,0.010190,0.009754,0.009834,0.009946,0.009965,0.009927,0.009938,0.009914,0.009910
Co_σ,0.009200,0.009561,0.009272,0.009007,0.009002,0.009235,0.009442,0.009512,0.009581
Al_Co_σ,0.011040,0.010189,0.009757,0.009795,0.009834,0.009865,0.009867,0.009875,0.009940
μmax,-0.091988,-0.071884,-0.071884,-0.071884,-0.071884,-0.071884,-0.071884,-0.071884,-0.071884
Al_Up_μ,-0.001040,-0.006094,-0.001987,0.002054,-0.001934,0.003004,0.001490,-0.002538,0.006576
Co_Up_μ,-0.006495,0.005418,-0.012649,0.022827,0.071092,0.069351,-0.052511,0.052744,-0.021357
Al_Do_μ,-0.091888,-0.071814,0.071674,-0.071728,-0.071785,0.071783,0.071837,-0.071752,-0.071548
Co_Do_μ,0.011590,0.070865,0.041267,0.056416,-0.070989,0.049272,-0.048433,-0.070213,-0.070669
Al_μ,0.088631,-0.060136,0.017705,-0.025584,0.049875,-0.014776,0.028206,0.056588,0.070948
Co_μ,-0.011173,-0.009693,-0.017424,-0.011417,-0.005427,-0.000465,-0.000576,0.001884,0.002166
Al_Co_μ,-0.017973,-0.008996,-0.017972,-0.012021,-0.005953,-0.000100,-0.000192,0.002390,0.002817

In [48]:
start = timeit.default_timer()
res0_rtbl = [uz.multfit_dist(pxchg0.loc[(h-1)*3600:h*3600], s, α, hours, h)
             for h in hour_range]
stop = timeit.default_timer()
print('Time Spent: ', round(stop - start), ' seconds')
df0_rrest = pd.concat(res0_rtbl, axis=0)

Time Spent:  763  seconds

In [49]:
df0_rrest.T

,1,2,3,4,5,6,7,8,9
Al_Up,0.294560,0.306723,0.312139,0.301278,0.306312,0.309260,0.298664,0.312390,0.303204
Co_Up,0.196759,0.180672,0.188439,0.202069,0.200926,0.189866,0.200465,0.191427,0.196224
Al_Do,0.294560,0.307323,0.312139,0.301278,0.306312,0.308678,0.298664,0.312977,0.303204
Co_Do,0.214120,0.205282,0.187283,0.195374,0.186450,0.192196,0.202208,0.183206,0.197368
Al,0.589120,0.614046,0.624277,0.602556,0.612623,0.617938,0.597327,0.625367,0.606407
Co,0.410880,0.385954,0.375723,0.397444,0.387377,0.382062,0.402673,0.374633,0.393593
Al_Co_dist,0.318013,0.349974,0.361536,0.378848,0.223526,0.258765,0.264102,0.277973,0.244618
H,0.348723,0.314272,0.300926,0.329798,0.316163,0.309142,0.337062,0.299531,0.324528
Al_Up_η,0.317640,0.269717,0.287000,0.329020,0.343324,0.335028,0.293006,0.356774,0.368401
Co_Up_η,0.244754,0.330574,0.174479,0.228863,0.252492,0.361110,0.368876,0.338325,0.355127
Al_Do_η,0.310952,0.278875,0.331610,0.342212,0.340122,0.303777,0.342603,0.325172,0.268385
Co_Do_η,0.353323,0.266849,0.212282,0.311373,0.320818,0.226282,0.379179,0.373543,0.325607
Al_η,0.314277,0.276445,0.320947,0.336559,0.342215,0.324826,0.313892,0.341258,0.313653
Co_η,0.293951,0.300326,0.189405,0.255153,0.292171,0.298818,0.372144,0.357496,0.337671
Al_Co_η,0.391982,0.290880,0.246523,0.331028,0.318232,0.324811,0.379835,0.341395,0.353521
σP,0.012494,0.012322,0.012540,0.012234,0.012520,0.012459,0.012503,0.012403,0.012561
σXe,0.010434,0.009769,0.009728,0.009936,0.009956,0.009797,0.010265,0.009600,0.010120
Al_Up_σ,0.010167,0.008693,0.009125,0.009703,0.010194,0.010475,0.009611,0.010619,0.010701
Co_Up_σ,0.007265,0.009950,0.008120,0.008689,0.008640,0.010395,0.009897,0.010799,0.011031
Al_Do_σ,0.010228,0.009480,0.010047,0.010580,0.010366,0.009607,0.010579,0.009655,0.009507
Co_Do_σ,0.010105,0.008824,0.006979,0.009160,0.010347,0.008590,0.011015,0.011767,0.009225
Al_σ,0.010192,0.009259,0.009838,0.010224,0.010257,0.010202,0.010029,0.010173,0.010049
Co_σ,0.009206,0.009357,0.007638,0.008450,0.009520,0.009592,0.010666,0.010658,0.010244
Al_Co_σ,0.011041,0.009189,0.008851,0.009888,0.010001,0.010091,0.010837,0.010359,0.010556
μmax,-0.091988,-0.112649,0.083750,0.104814,0.057140,0.048746,-0.117330,0.091596,-0.139741
Al_Up_μ,0.001660,0.112375,0.005036,0.002698,-0.003330,-0.005615,0.117298,0.091282,0.001974
Co_Up_μ,-0.091548,-0.013446,0.083639,0.104595,0.010317,-0.009877,-0.081851,0.091039,0.072876
Al_Do_μ,-0.091937,0.112331,0.000116,-0.000591,-0.056927,-0.008064,-0.116735,0.000022,0.139640
Co_Do_μ,0.007403,-0.027817,0.083689,0.041470,-0.008249,-0.030092,-0.038338,-0.091356,0.087272
Al_μ,-0.087533,0.092463,0.016746,0.008015,-0.050980,0.022364,0.117263,0.000421,-0.139393
Co_μ,-0.011140,-0.016859,-0.022827,0.003098,0.023938,0.028994,-0.008286,0.022435,0.007366
Al_Co_μ,-0.018029,-0.016461,-0.029045,0.003606,0.026116,0.031457,-0.007223,0.021715,0.007392

In [50]:
start = timeit.default_timer()
res1_rtbl = [uz.multfit_dist(pxchg1.loc[(h-1)*3600:h*3600], s, α, hours, h)
             for h in hour_range]
stop = timeit.default_timer()
print('Time Spent: ', round(stop - start), ' seconds')
df1_rrest = pd.concat(res1_rtbl, axis=0)

Time Spent:  805  seconds

In [51]:
df1_rrest.T

,1,2,3,4,5,6,7,8,9
Al_Up,0.294560,0.306723,0.312139,0.301278,0.296117,0.303219,0.298760,0.298549,0.296954
Co_Up,0.196759,0.180672,0.188439,0.202069,0.208981,0.196326,0.200775,0.203556,0.202663
Al_Do,0.294560,0.307323,0.312139,0.301278,0.296117,0.303067,0.298760,0.298705,0.296954
Co_Do,0.214120,0.205282,0.187283,0.195374,0.198786,0.197388,0.201705,0.199189,0.203429
Al,0.589120,0.614046,0.624277,0.602556,0.592233,0.606286,0.597519,0.597255,0.593908
Co,0.410880,0.385954,0.375723,0.397444,0.407767,0.393714,0.402481,0.402745,0.406092
Al_Co_dist,0.318014,0.349979,0.361536,0.378847,0.346732,0.029414,0.036810,0.020753,0.027246
H,0.348723,0.314272,0.300926,0.329798,0.344262,0.324693,0.336793,0.337164,0.341881
Al_Up_η,0.317659,0.269894,0.287095,0.329029,0.188978,0.358603,0.364825,0.342533,0.332642
Co_Up_η,0.245089,0.330768,0.293669,0.229166,0.500000,0.366029,0.352007,0.348716,0.351695
Al_Do_η,0.310841,0.278888,0.331538,0.342154,0.209749,0.342942,0.334792,0.346606,0.340224
Co_Do_η,0.353229,0.270326,0.211858,0.312460,0.499994,0.288167,0.330734,0.307488,0.343133
Al_η,0.313873,0.276446,0.320654,0.336735,0.205007,0.348920,0.353989,0.343633,0.335556
Co_η,0.293751,0.300406,0.189889,0.255269,0.500000,0.347061,0.341131,0.333259,0.348732
Al_Co_η,0.392015,0.290895,0.246526,0.330796,0.266462,0.325407,0.325092,0.343552,0.337446
σP,0.012494,0.012322,0.012540,0.012234,0.019306,0.024364,0.024200,0.023998,0.024206
σXe,0.010434,0.009769,0.009728,0.009936,0.016020,0.019634,0.019862,0.019707,0.020016
Al_Up_σ,0.010167,0.008695,0.009126,0.009703,0.012891,0.020231,0.020485,0.019990,0.019609
Co_Up_σ,0.007266,0.009734,0.002115,0.008696,0.020136,0.021052,0.021381,0.019291,0.020529
Al_Do_σ,0.010226,0.009480,0.010046,0.010578,0.013400,0.020041,0.019395,0.020041,0.020156
Co_Do_σ,0.010012,0.007211,0.008580,0.008489,0.020885,0.017952,0.020573,0.018903,0.020868
Al_σ,0.010184,0.009255,0.009833,0.010228,0.013289,0.020115,0.020107,0.020005,0.019827
Co_σ,0.009202,0.009358,0.007649,0.008452,0.020494,0.020442,0.020105,0.019630,0.020337
Al_Co_σ,0.011041,0.009188,0.008851,0.009882,0.014714,0.019619,0.019496,0.019998,0.019934
μmax,-0.091988,-0.112649,0.083750,0.104814,0.088315,0.098599,-0.238343,0.174828,-0.282426
Al_Up_μ,0.002136,-0.112440,0.001900,-0.000611,0.088219,-0.005069,-0.154004,0.009887,0.022820
Co_Up_μ,-0.091938,-0.037655,-0.058287,0.104725,0.008479,0.008672,0.231971,-0.145109,0.077183
Al_Do_μ,0.091907,-0.112298,0.002667,-0.014811,0.087532,0.008307,-0.032549,-0.023046,0.013289
Co_Do_μ,0.017792,0.112587,-0.083546,0.099246,0.007114,0.092798,-0.220398,0.002733,-0.127038
Al_μ,0.091357,-0.110205,0.009960,0.002637,0.088015,0.015975,-0.021794,0.021961,0.062702
Co_μ,-0.011146,-0.016915,-0.022909,0.003073,0.085090,0.020545,-0.002838,0.050322,0.054374
Al_Co_μ,-0.018052,-0.016481,-0.028872,0.003690,0.057715,0.017895,-0.001645,0.052367,0.052713

In [52]:
start = timeit.default_timer()
res2_rtbl = [uz.multfit_dist(pxchg2.loc[(h-1)*3600:h*3600], s, α, hours, h)
             for h in hour_range]
stop = timeit.default_timer()
print('Time Spent: ', round(stop - start), ' seconds')
df2_rrest = pd.concat(res2_rtbl, axis=0)

Time Spent:  707  seconds

In [53]:
df2_rrest.T

,1,2,3,4,5,6,7,8,9
Al_Up,0.294560,0.306723,0.312139,0.301278,0.304142,0.304828,0.308934,0.307823,0.305223
Co_Up,0.196759,0.180672,0.188439,0.202069,0.211243,0.210588,0.206340,0.212018,0.209467
Al_Do,0.294560,0.307323,0.312139,0.301278,0.304142,0.304828,0.308357,0.308390,0.305223
Co_Do,0.214120,0.205282,0.187283,0.195374,0.180473,0.179756,0.176369,0.171769,0.180087
Al,0.589120,0.614046,0.624277,0.602556,0.608284,0.609657,0.617291,0.616213,0.610446
Co,0.410880,0.385954,0.375723,0.397444,0.391716,0.390343,0.382709,0.383787,0.389554
Al_Co_dist,0.318014,0.349976,0.361537,0.378846,0.273980,0.379201,0.230683,0.170574,0.209341
H,0.348723,0.314272,0.300926,0.329798,0.321984,0.320134,0.309991,0.311408,0.319073
Al_Up_η,0.317554,0.269801,0.286994,0.328892,0.253602,0.220320,0.323189,0.330880,0.348673
Co_Up_η,0.243773,0.331147,0.174292,0.231961,0.243767,0.281588,0.163963,0.401892,0.371966
Al_Do_η,0.310929,0.278982,0.331657,0.341902,0.368613,0.354826,0.304226,0.333446,0.252453
Co_Do_η,0.353556,0.267476,0.212604,0.311793,0.336961,0.193247,0.409866,0.385753,0.302131
Al_η,0.314519,0.275930,0.321348,0.337273,0.331058,0.298382,0.312860,0.332710,0.322790
Co_η,0.293927,0.300326,0.189391,0.255436,0.297496,0.253984,0.264847,0.397020,0.343222
Al_Co_η,0.392072,0.291261,0.246444,0.330933,0.291121,0.320541,0.287031,0.334752,0.353323
σP,0.012494,0.012322,0.012540,0.012234,0.012372,0.012405,0.012417,0.012408,0.012595
σXe,0.010434,0.009769,0.009728,0.009936,0.009929,0.009926,0.009777,0.009792,0.010062
Al_Up_σ,0.010165,0.008694,0.009125,0.009701,0.008759,0.008393,0.010021,0.010248,0.010906
Co_Up_σ,0.009018,0.009690,0.008110,0.006537,0.008740,0.009587,0.007630,0.009850,0.010224
Al_Do_σ,0.010228,0.009481,0.010048,0.010576,0.010460,0.010594,0.009567,0.010306,0.009395
Co_Do_σ,0.010202,0.008119,0.008596,0.009216,0.010387,0.008459,0.012859,0.010916,0.010146
Al_σ,0.010212,0.009236,0.009842,0.010230,0.009951,0.009753,0.009779,0.010317,0.010511
Co_σ,0.009205,0.009357,0.007637,0.008456,0.009566,0.008676,0.009150,0.011456,0.010667
Al_Co_σ,0.011042,0.009195,0.008850,0.009884,0.009427,0.010014,0.009541,0.010331,0.010890
μmax,-0.091988,-0.112649,0.083750,0.104814,0.064217,0.099919,0.113226,0.121129,0.095375
Al_Up_μ,-0.003049,-0.112635,-0.003000,-0.002511,-0.063997,0.099888,-0.113213,0.005560,-0.004816
Co_Up_μ,0.091891,-0.042936,0.082849,-0.104738,0.063419,0.099724,0.113185,-0.102618,-0.041572
Al_Do_μ,0.091914,-0.112254,-0.000123,0.003031,0.064086,-0.099166,-0.113192,-0.120654,-0.095342
Co_Do_μ,-0.003549,0.047995,-0.083457,0.036683,0.031850,-0.099673,-0.111743,0.118174,0.041361
Al_μ,0.049984,-0.112628,0.013574,-0.006684,0.062846,-0.099628,-0.112038,-0.000825,-0.092130
Co_μ,-0.011232,-0.016848,-0.022869,0.003092,0.037049,0.043059,0.022393,0.086957,0.077017
Al_Co_μ,-0.017915,-0.016519,-0.028960,0.003749,0.036525,0.055631,0.023513,0.075393,0.080416

In [54]:
start = timeit.default_timer()
res4_rtbl = [uz.multfit_dist(pxchg4.loc[(h-1)*3600:h*3600], s, α, hours, h)
             for h in hour_range]
stop = timeit.default_timer()
print('Time Spent: ', round(stop - start), ' seconds')
df4_rrest = pd.concat(res4_rtbl, axis=0)

Time Spent:  722  seconds

In [55]:
df4_rrest.T

,1,2,3,4,5,6,7,8,9
Al_Up,0.294560,0.306723,0.312139,0.301693,0.305416,0.306622,0.309642,0.311761,0.304005
Co_Up,0.196759,0.180672,0.188439,0.204353,0.269123,0.194769,0.189532,0.192459,0.195149
Al_Do,0.294560,0.307323,0.312139,0.301693,0.304858,0.307179,0.309091,0.312324,0.304005
Co_Do,0.214120,0.205282,0.187283,0.192261,0.120603,0.191430,0.191736,0.183455,0.196842
Al,0.589120,0.614046,0.624277,0.603386,0.610274,0.613801,0.618733,0.624086,0.608009
Co,0.410880,0.385954,0.375723,0.396614,0.389726,0.386199,0.381267,0.375914,0.391991
Al_Co_dist,0.318015,0.349974,0.361539,0.407332,0.295165,0.151701,0.226160,0.290595,0.175162
H,0.348723,0.314272,0.300926,0.328657,0.319305,0.314597,0.308103,0.301172,0.322356
Al_Up_η,0.317617,0.269882,0.287315,0.335510,0.324320,0.292515,0.364823,0.344725,0.303759
Co_Up_η,0.243811,0.330731,0.296949,0.226988,0.322371,0.291804,0.247003,0.408039,0.287108
Al_Do_η,0.310821,0.278965,0.331754,0.355487,0.362334,0.313468,0.301515,0.352387,0.372415
Co_Do_η,0.353511,0.270091,0.211498,0.312358,0.374995,0.307215,0.260204,0.246016,0.313098
Al_η,0.314022,0.276172,0.320896,0.346345,0.345002,0.304996,0.348449,0.349270,0.325992
Co_η,0.293773,0.300378,0.189362,0.257202,0.327797,0.302056,0.253633,0.333856,0.240621
Al_Co_η,0.392181,0.291047,0.246579,0.330267,0.277911,0.302413,0.270977,0.276813,0.302865
σP,0.012494,0.012322,0.012540,0.012282,0.012576,0.012427,0.012526,0.012339,0.012322
σXe,0.010434,0.009769,0.009728,0.009957,0.010050,0.009858,0.009832,0.009577,0.009894
Al_Up_σ,0.010168,0.008695,0.009129,0.009776,0.009975,0.009701,0.010721,0.010227,0.009849
Co_Up_σ,0.009019,0.009812,0.002055,0.007857,0.007052,0.009951,0.009044,0.011205,0.009557
Al_Do_σ,0.010226,0.009481,0.010049,0.010826,0.010813,0.010139,0.009780,0.010371,0.010709
Co_Do_σ,0.010149,0.007204,0.008571,0.008592,0.012722,0.010306,0.008161,0.008919,0.001857
Al_σ,0.010186,0.009248,0.009837,0.010373,0.010440,0.009961,0.010470,0.010311,0.010117
Co_σ,0.009202,0.009358,0.007637,0.008529,0.010622,0.009928,0.009209,0.010704,0.008654
Al_Co_σ,0.011043,0.009192,0.008852,0.009913,0.009541,0.009932,0.009525,0.009485,0.009906
μmax,-0.091988,-0.112649,0.083750,0.104814,0.254525,0.049896,-0.120125,0.072114,-0.142790
Al_Up_μ,-0.002132,0.112575,0.005585,-0.003392,-0.012241,-0.049618,0.004742,0.002581,-0.142546
Co_Up_μ,0.091924,-0.029246,-0.055737,0.003778,-0.125756,0.045221,0.000669,-0.071117,0.008049
Al_Do_μ,-0.091918,-0.112371,-0.001687,-0.003080,0.005515,0.002261,-0.120100,0.005618,-0.001740
Co_Do_μ,0.002610,0.112620,-0.083417,0.103234,0.188148,-0.019017,0.113402,0.023653,0.046687
Al_μ,0.090222,0.111455,0.007872,-0.011268,0.011373,-0.035737,0.094908,-0.002555,0.141997
Co_μ,-0.011177,-0.016901,-0.022824,0.012280,0.254512,0.015744,0.003264,0.029623,0.012615
Al_Co_μ,-0.017810,-0.016450,-0.028947,0.015034,0.209370,0.015743,0.004480,0.027527,0.014531

In [56]:
start = timeit.default_timer()
res5_rtbl = [uz.multfit_dist(pxchg5.loc[(h-1)*3600:h*3600], s, α, hours, h)
             for h in hour_range]
stop = timeit.default_timer()
print('Time Spent: ', round(stop - start), ' seconds')
df5_rrest = pd.concat(res4_rtbl, axis=0)

Time Spent:  732  seconds

In [57]:
df5_rrest.T

,1,2,3,4,5,6,7,8,9
Al_Up,0.294560,0.306723,0.312139,0.301693,0.305416,0.306622,0.309642,0.311761,0.304005
Co_Up,0.196759,0.180672,0.188439,0.204353,0.269123,0.194769,0.189532,0.192459,0.195149
Al_Do,0.294560,0.307323,0.312139,0.301693,0.304858,0.307179,0.309091,0.312324,0.304005
Co_Do,0.214120,0.205282,0.187283,0.192261,0.120603,0.191430,0.191736,0.183455,0.196842
Al,0.589120,0.614046,0.624277,0.603386,0.610274,0.613801,0.618733,0.624086,0.608009
Co,0.410880,0.385954,0.375723,0.396614,0.389726,0.386199,0.381267,0.375914,0.391991
Al_Co_dist,0.318015,0.349974,0.361539,0.407332,0.295165,0.151701,0.226160,0.290595,0.175162
H,0.348723,0.314272,0.300926,0.328657,0.319305,0.314597,0.308103,0.301172,0.322356
Al_Up_η,0.317617,0.269882,0.287315,0.335510,0.324320,0.292515,0.364823,0.344725,0.303759
Co_Up_η,0.243811,0.330731,0.296949,0.226988,0.322371,0.291804,0.247003,0.408039,0.287108
Al_Do_η,0.310821,0.278965,0.331754,0.355487,0.362334,0.313468,0.301515,0.352387,0.372415
Co_Do_η,0.353511,0.270091,0.211498,0.312358,0.374995,0.307215,0.260204,0.246016,0.313098
Al_η,0.314022,0.276172,0.320896,0.346345,0.345002,0.304996,0.348449,0.349270,0.325992
Co_η,0.293773,0.300378,0.189362,0.257202,0.327797,0.302056,0.253633,0.333856,0.240621
Al_Co_η,0.392181,0.291047,0.246579,0.330267,0.277911,0.302413,0.270977,0.276813,0.302865
σP,0.012494,0.012322,0.012540,0.012282,0.012576,0.012427,0.012526,0.012339,0.012322
σXe,0.010434,0.009769,0.009728,0.009957,0.010050,0.009858,0.009832,0.009577,0.009894
Al_Up_σ,0.010168,0.008695,0.009129,0.009776,0.009975,0.009701,0.010721,0.010227,0.009849
Co_Up_σ,0.009019,0.009812,0.002055,0.007857,0.007052,0.009951,0.009044,0.011205,0.009557
Al_Do_σ,0.010226,0.009481,0.010049,0.010826,0.010813,0.010139,0.009780,0.010371,0.010709
Co_Do_σ,0.010149,0.007204,0.008571,0.008592,0.012722,0.010306,0.008161,0.008919,0.001857
Al_σ,0.010186,0.009248,0.009837,0.010373,0.010440,0.009961,0.010470,0.010311,0.010117
Co_σ,0.009202,0.009358,0.007637,0.008529,0.010622,0.009928,0.009209,0.010704,0.008654
Al_Co_σ,0.011043,0.009192,0.008852,0.009913,0.009541,0.009932,0.009525,0.009485,0.009906
μmax,-0.091988,-0.112649,0.083750,0.104814,0.254525,0.049896,-0.120125,0.072114,-0.142790
Al_Up_μ,-0.002132,0.112575,0.005585,-0.003392,-0.012241,-0.049618,0.004742,0.002581,-0.142546
Co_Up_μ,0.091924,-0.029246,-0.055737,0.003778,-0.125756,0.045221,0.000669,-0.071117,0.008049
Al_Do_μ,-0.091918,-0.112371,-0.001687,-0.003080,0.005515,0.002261,-0.120100,0.005618,-0.001740
Co_Do_μ,0.002610,0.112620,-0.083417,0.103234,0.188148,-0.019017,0.113402,0.023653,0.046687
Al_μ,0.090222,0.111455,0.007872,-0.011268,0.011373,-0.035737,0.094908,-0.002555,0.141997
Co_μ,-0.011177,-0.016901,-0.022824,0.012280,0.254512,0.015744,0.003264,0.029623,0.012615
Al_Co_μ,-0.017810,-0.016450,-0.028947,0.015034,0.209370,0.015743,0.004480,0.027527,0.014531

In [ ]:
df0_rest['H'].plot(color='c');
df0_rrest['H'].plot(color='k');
df1_rrest['H'].plot(color='g');
df2_rrest['H'].plot(color='b');
df4_rrest['H'].plot(color='r');
df5_rrest['H'].plot(color='y');

In [ ]:
df0_rest['η'].plot(color='c');
df0_rrest['η'].plot(color='k');
df1_rrest['η'].plot(color='g');
df2_rrest['η'].plot(color='b');
df4_rrest['η'].plot(color='r');
df5_rrest['η'].plot(color='y');

In [ ]:
df_rest['σ'].plot(color='c');
df_rrest['σ'].plot(color='k');
df1_rrest['σ'].plot(color='g');
df2_rrest['σ'].plot(color='b');
df4_rrest['σ'].plot(color='r');
df5_rrest['σ'].plot(color='y');

In [ ]:
df0_rrest['μ'].plot(color='k');
df1_rrest['μ'].plot(color='g');
df2_rrest['μ'].plot(color='b');
df4_rrest['μ'].plot(color='r');
df5_rrest['μ'].plot(color='y');

In [ ]:
df4_rmrest['η'].plot(color='r');
df5_rmrest['η'].plot(color='y');

In [ ]:
df4_rmrest['σ'].plot(color='r');
df5_rmrest['σ'].plot(color='y');

In [ ]:
df4_rmrest['μ'].plot(color='r');
df5_rmrest['μ'].plot(color='y');

In [ ]:
uz.qq_plots(pxchg0, s, α, η, σ, μ, hours)

In [ ]:
uz.qq_plots(pxchg0, s, α, 0.327, 0.01, 0, hours)

In [ ]:
uz.cum_H(pxchg0).plot(figsize=(9, 6), color='k');
uz.cum_H(pxchg1).plot(figsize=(9, 6), color='g');
uz.cum_H(pxchg2).plot(figsize=(9, 6), color='b');
uz.cum_H(pxchg3).plot(figsize=(9, 6), color='m');
uz.cum_H(pxchg4).plot(figsize=(9, 6), color='r');

In [ ]:
uz.cum_H(pxchg0).loc[5000:].plot(figsize=(9, 6), color='k');
uz.cum_H(pxchg1).loc[5000:].plot(figsize=(9, 6), color='g');
uz.cum_H(pxchg2).loc[5000:].plot(figsize=(9, 6), color='b');
uz.cum_H(pxchg3).loc[5000:].plot(figsize=(9, 6), color='m');
uz.cum_H(pxchg4).loc[5000:].plot(figsize=(9, 6), color='r');

In [ ]:

def rolling_indic(df, window=100):
    dfc = df.copy()
    dfc['dPtj_r'] = dfc['dPtj'].rolling(window=window).sum()
    dfc['Co_r'] = dfc['Co'].rolling(window=window).sum()
    dfc['Al_r'] = dfc['Al'].rolling(window=window).sum()
    dfc['H_r'] = dfc['Co_r'] / (2 * dfc['Al_r'])
    dfc['dtj_Co'] = np.where(dfc['Co'], dfc['dtj'], 0)
    dfc['dtj_Al'] = np.where(dfc['Al'], dfc['dtj'], 0)
    dfc['dtj_Co_r'] = dfc['dtj_Co'].rolling(window=window).sum() / dfc['Co_r']
    dfc['dtj_Al_r'] = dfc['dtj_Al'].rolling(window=window).sum() / dfc['Al_r']
    dfc['dtj_Co/Al_r'] = dfc['dtj_Co_r'] / dfc['dtj_Al_r']
    dfc['eta_r'] = (np.sqrt(dfc['dtj_Co/Al_r']**2 - dfc['dtj_Co/Al_r'] + 1) +
                    (1 - dfc['dtj_Co/Al_r'])) / (2 * dfc['dtj_Co/Al_r'])
    return dfc

In [ ]:

window_roll = 500

pxchg0_r = rolling_indic(pxchg0, window_roll)
pxchg1_r = rolling_indic(pxchg1, window_roll)
pxchg2_r = rolling_indic(pxchg2, window_roll)
pxchg3_r = rolling_indic(pxchg3, window_roll)
pxchg4_r = rolling_indic(pxchg4, window_roll)

In [ ]:

pxchg0_r['dPtj_r'].plot(figsize=(9, 6), color='k');
pxchg1_r['dPtj_r'].plot(figsize=(9, 6), color='g');
pxchg2_r['dPtj_r'].plot(figsize=(9, 6), color='b');
pxchg3_r['dPtj_r'].plot(figsize=(9, 6), color='m');
pxchg4_r['dPtj_r'].plot(figsize=(9, 6), color='r');

In [ ]:

pxchg0_r['H_r'].plot(figsize=(9, 6), color='k');
pxchg1_r['H_r'].plot(figsize=(9, 6), color='g');
pxchg2_r['H_r'].plot(figsize=(9, 6), color='b');
pxchg3_r['H_r'].plot(figsize=(9, 6), color='m');
pxchg4_r['H_r'].plot(figsize=(9, 6), color='r');

In [ ]:

pxchg0_r['dtj_Al_r'].plot(figsize=(9, 6), color='k');
pxchg1_r['dtj_Al_r'].plot(figsize=(9, 6), color='g');
pxchg2_r['dtj_Al_r'].plot(figsize=(9, 6), color='b');
pxchg3_r['dtj_Al_r'].plot(figsize=(9, 6), color='m');
pxchg4_r['dtj_Al_r'].plot(figsize=(9, 6), color='r');

In [ ]:

pxchg0_r['dtj_Co_r'].plot(figsize=(9, 6), color='k');
pxchg1_r['dtj_Co_r'].plot(figsize=(9, 6), color='g');
pxchg2_r['dtj_Co_r'].plot(figsize=(9, 6), color='b');
pxchg3_r['dtj_Co_r'].plot(figsize=(9, 6), color='m');
pxchg4_r['dtj_Co_r'].plot(figsize=(9, 6), color='r');

In [ ]:

(pxchg0_r['dtj_Co_r'] / pxchg0_r['dtj_Al_r']).plot(figsize=(9, 6), color='k');
(pxchg1_r['dtj_Co_r'] / pxchg1_r['dtj_Al_r']).plot(figsize=(9, 6), color='g');
(pxchg2_r['dtj_Co_r'] / pxchg2_r['dtj_Al_r']).plot(figsize=(9, 6), color='b');
(pxchg3_r['dtj_Co_r'] / pxchg3_r['dtj_Al_r']).plot(figsize=(9, 6), color='m');
(pxchg4_r['dtj_Co_r'] / pxchg4_r['dtj_Al_r']).plot(figsize=(9, 6), color='r');

In [ ]:

pxchg0_r['eta_r'].plot(figsize=(9, 6), color='k', linestyle=':');
pxchg1_r['eta_r'].plot(figsize=(9, 6), color='g');
pxchg2_r['eta_r'].plot(figsize=(9, 6), color='b');
pxchg3_r['eta_r'].plot(figsize=(9, 6), color='m');
pxchg4_r['eta_r'].plot(figsize=(9, 6), color='r', linestyle=':');

In [ ]:

algo_tr = rpt.Pelt(model='l2', min_size=100).fit(pxchg2['dtj'].dropna().values)
my_bkps_tr = algo_tr.predict(pen=3)

In [ ]:

rpt.display(pxchg2['dtj'].dropna().values, my_bkps_tr)